name: 'Continuous Integration'

on:
  push:
  workflow_dispatch:

jobs:
  build-test:
    name: Application build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          architecture: x64

      - name: Build
        run: mvn clean package -DskipTests

      - name: Run unit tests
        run: mvn test